# Generated by Django 5.2.6 on 2025-09-09 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('corpo', models.TextField(verbose_name='Corpo do conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='Status')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('duracao_dias', models.PositiveIntegerField(default=7, verbose_name='Duração (dias)')),
                ('recompensa', models.CharField(blank=True, max_length=200, verbose_name='Recompensa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DiarioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de registro')),
                ('tempo_total_min', models.PositiveIntegerField(default=0, verbose_name='Tempo de uso (minutos)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Reflexão')),
                ('humor', models.CharField(blank=True, max_length=100, verbose_name='Humor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Entrada de Diário',
                'verbose_name_plural': 'Diário',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('relato', models.TextField(verbose_name='Relato')),
                ('idade_aprox', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade aproximada')),
                ('anonimo', models.BooleanField(default=True, verbose_name='Anônimo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('moderado', models.BooleanField(default=False, verbose_name='Aprovado pela moderação')),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespiracaoExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('instrucoes', models.TextField(verbose_name='Instruções')),
                ('duracao_segundos', models.PositiveIntegerField(default=60, verbose_name='Duração (segundos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Exercício de Respiração',
                'verbose_name_plural': 'Exercícios de Respiração',
                'ordering': ['titulo'],
            },
        ),
    ]
