# Generated by Django 5.2.6 on 2025-09-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_feedback_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={},
        ),
        migrations.AddField(
            model_name='conteudo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Vídeo (YouTube/Vimeo)'),
        ),
    ]
