# Generated by Django 5.2.6 on 2025-09-30 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_conteudo_options_conteudo_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'ordering': ['-publicado_em', '-criado_em'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografia'),
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
