# Generated by Django 5.2.6 on 2025-10-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_conteudo_options_alter_perfil_bio_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioentry',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='app.desafio'),
        ),
        migrations.AddField(
            model_name='relato',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='app.conteudo'),
        ),
    ]
