# Generated by Django 5.2.6 on 2025-10-21 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_diarioentry_desafio_relato_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='diario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='app.perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relato',
            name='conteudo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='app.conteudo'),
            preserve_default=False,
        ),
    ]
