# Generated by Django 5.2.7 on 2025-10-21 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_diario_usuario_diario_criado_em_diario_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diario',
            options={'ordering': ['-data'], 'verbose_name': 'Entrada de Diário', 'verbose_name_plural': 'Diário'},
        ),
        migrations.AddField(
            model_name='conteudo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='DiarioEntry',
        ),
    ]
